// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"globalfunctions","status":true,"description":"Define funções globais para uso em todo o jogo.","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Iavra Self Variables","status":true,"description":"Adds self variables to the game, that work similar to self switches.\r\n<Iavra Self Variables>","parameters":{"Container Name":"$gameSelfVariables","Plugin Command":"SelfVariable"}},
{"name":"HIME_CustomPageConditions","status":true,"description":"v1.6 - Create your own page conditions for your events using\r\nregular eventing!","parameters":{}}
];
